name: Build flipSnapshotTestUtils

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build flipSnapshotTestUtils
    permissions:
      checks: write
      contents: read
    uses: Displayr/nixr-public/.github/workflows/build-flake-installable.yaml@master
    with:
      installable-path: pkgs.x86_64-linux.rPackages.flipSnapshotTestUtils
      build-args: --override-input flipSnapshotTestUtils .
      installable-name: flipSnapshotTestUtils
    secrets: inherit
